### ISSUE TITLE
Уведомление при подаче заявки на верификацию карты

### ISSUE THREAD

**Issue by JohnWick88** [finfex/larry#11]
При верификации карты уведомление сверху должно выдавать ошибку и подсвечиваться красным если:
- в поле номер карты - введены не все цифры
- в поле имя на карте - написано по русски
- не прикреплен файл

<img width="1158" alt="Screenshot 2021-07-31 at 12 31 21" src="https://user-images.githubusercontent.com/88229668/127736205-96c02a92-ea2a-40bd-90bb-9e8e2b118490.png">

**Comment by dapi** [comment]
Дай плиз ссылку на пример такой верификации

**Comment by JohnWick88** [comment]
Пока нет необходимсти в данной функции

**Comment by JohnWick88** [comment]
Пока нет необходимсти в данной функции
