### ISSUE TITLE
Добавить поле для платежной системы

### ISSUE THREAD

**Issue by JohnWick88** [finfex/larry#17]
При выборе плетжной системы "Наличные RUB", на главной в разделе "3. Ввод данных", 
Добавить выпадающее поле Город (c единственным городом Москва).
Поля для ПС  "Наличные RUB":
1. Город
2. ФИО
3. Email
4. Telegram
5. Телефон

**Comment by dapi** [comment]
Получается что не хватает только Город, Telegram, Телефон? И при этом город должен из выпадающего списка?

**Comment by JohnWick88** [comment]
пока норм
